### PR TITLE
Readme cleanup

### PR DESCRIPTION
**Pull request by kremalicious**
200w

- add repo banner
- badges. Cause badges
- nicer code formatting all around
- switch to `const`
- add installation instructions
- more useful bundled version example
- rename repo
- remove node/browser distinction
- update urls

### One more thing: npm releases

unknown

Just crank in your Terminal:

```bash
# patch release
npm run release

# minor release
npm run release-minor

#major release
npm run release-major
```

Which does this without user interaction:

- create release commit by updating version in package.json
- create tag for that release commit
- push commit & tag
- create a new release on GitHub, with change log auto-generated from commit messages
- publish to npm as a new release

### CODE REVIEW

**Comment by kremalicious** [comment]
@diminator what do you think about renaming the repo and removing the `js-`? Lemme explain:

1. using `ilp-plugin-bigchaindb` reflects the syntax used by all the other ILP ledger plugins over here: https://github.com/interledgerjs
2. would then also reflect the actual package name used in npm making it less confusing for new users

Agree?

**Comment by diminator** [comment]
I was thinking the same

**Comment by kremalicious** [comment]
done. Guess for more simplicity we could start providing only one build but works for now for flexibility. Also trying to fix eslint right now but gonna do that in another PR so this one's good to go.

Renamed repo on GitHub, good first test to see consequences of that. In theory GitHub should put a redirect in place

**Comment by kremalicious** [comment]
@diminator although adding an extended usage example would be awesome. Like this one, which is great: https://github.com/bigchaindb/js-bigchaindb-driver#usage

So feel free to add, otherwise later and merge this PR

**Pull request merged**
