### PR TITLE
Upgrade/ilp kit

### PR DESCRIPTION
**Pull request by diminator**
upgrade towards ilp-kit

@kremalicious can you check the changes you made:
- eslint
- bundle for cjs/es6
- publish minor/major

### CODE REVIEW

**Comment by kremalicious** [comment]
I'm sorry but I don't see anything in this PR I have done

**Review by kremalicious — CHANGES_REQUESTED** [review]
sorry, now I get it, bit distracted here answering 2 other questions and Sylvain explaining me the details of crafting a transaction, all at the same time.

Have only one request: please add the test command to `package.json`. Then Travis should run that, so needs to be added to .travis.yml too. 

- eslint: linting works, but code is actually not properly linted. Hasn't been before so let's ignore for now. I can do another linting PR, once we throw out semicolons in ascribe/javascript first (Alberto requested that and I agree)
- bundling: wasn't any change I did there so should work as before
- npm releases: your changes won't affect anything regarding that. Would just make sure to always have proper commit messages, cause those will be used to create the changelog on GitHub

**Comment by diminator** [comment]
> please add the test command to package.json. Then Travis should run that, so needs to be added to .travis.yml too.

that's include from your PR on master... however travis is failing on `npm install` for some obscure reason

**Comment by kremalicious** [comment]
> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

https://travis-ci.org/bigchaindb/ilp-plugin-bigchaindb/builds/240043943#L552

So guess webpack dependency got updated and we use deprecated commands

**Comment by kremalicious** [comment]
Regarding `npm test`: that's our test command right now, just a placeholder: https://github.com/bigchaindb/ilp-plugin-bigchaindb/blob/master/package.json#L40

Right now this should run eslint & your newly created test file. And that then needs to be added to travis file, so it runs before build command: https://github.com/bigchaindb/ilp-plugin-bigchaindb/blob/master/.travis.yml#L7

Also think the `clean` command I put in there is redundant since build output is not cached on Travis so you could just replace that with `npm test`

**Comment by diminator** [comment]
ok, got most of them...

had some problems with uglify + harmony > but thats resolved now

**Comment by kremalicious** [comment]
Awesome, thanks. Still weird stuff on Travis, some part of npm install actually errors but build runs through, so YOLO for now

**Pull request merged**
